#ifndef WIDGET_H
#define WIDGET_H

#include <QWidget>

QT_BEGIN_NAMESPACE
namespace Ui { //TEST! // Trae: This is a forward declaration of a class that will be generated by Qt's UI compiler.
    class Widget;
}
QT_END_NAMESPACE

class Widget : public QWidget {
    Q_OBJECT
    Ui::Widget *ui;
    int secret_number = 0;
    int guess_number = 0;
public:
    Widget(QWidget *parent = nullptr);
    ~Widget();
private slots:
    void on_guessButton_clicked();
    void on_startOverButton_clicked();
};
#endif // WIDGET_H
